# Generated by Django 2.1.4 on 2019-02-14 09:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('author', models.CharField(max_length=32, verbose_name='文章作者')),
                ('time', models.DateField(verbose_name='发表时间')),
                ('discription', ckeditor.fields.RichTextField(verbose_name='文章描述')),
                ('content', ckeditor.fields.RichTextField(verbose_name='文章内容')),
                ('picture', models.ImageField(upload_to='', verbose_name='文章图片')),
                ('type', models.CharField(max_length=32, verbose_name='文章类型')),
                ('favor', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
        ),
    ]
