# Generated by Django 2.1.4 on 2019-02-18 10:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('author', models.CharField(max_length=32, verbose_name='文章作者')),
                ('time', models.DateField(verbose_name='发表时间')),
                ('discription', ckeditor.fields.RichTextField(verbose_name='文章描述')),
                ('content', ckeditor.fields.RichTextField(verbose_name='文章内容')),
                ('picture', models.ImageField(upload_to='', verbose_name='文章图片')),
                ('favor', models.IntegerField(default=0, verbose_name='点赞数')),
                ('recommend', models.BooleanField(verbose_name='推荐')),
                ('articleType', models.CharField(choices=[('selfDiary', '个人日记'), ('skillDiary', '学习笔记'), ('skillArticle', '技术文章'), ('diary', '个人简介')], max_length=32, verbose_name='文章类型')),
                ('articleFamily', models.CharField(choices=[('diary', '原创'), ('diary', '转载')], max_length=32, verbose_name='文章类型')),
            ],
        ),
    ]
